
name: Cypress Tests with Cucumber and Allure


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run || true
        env:
          CI: true
          

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports
          path: cypress/reports